name: " Database Service Deployment Workflow"

on:
  push:
    branches:
      - dev
      - testing
      - main
    paths:
      - "services/database/**"

jobs:
  build-and-push-to-Doceker_Hub:
    name: " Build The docker image and push to  Docker Hub"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setting up the Docker Build"
        uses: docker/setup-buildx-action@v3

      - name: " Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Determine Environment Tag"
        id: vars
        run: |
          if [[ $"GITHUB_REF_NAME" == "dev" ]]; then
            echo "ENV_TAG=dev" >> $GITHUB_ENV
          elif [[ $"GITHUB_REF_NAME" == "testing" ]]; then
            echo "ENV_TAG=testing" >> $GITHUB_ENV
          else
            echo "ENV_TAG=latest" >> $GITHUB_ENV
          fi

      - name: " Build and Push Docker Image"
        uses: docker/build-push-action@v4
        with:
          context: ./packages/database
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservice:database:-${{ env.ENV_TAG }}
