name: Tenanr service Docker image build and push

on:
    push:
        branches:
            - dev
            - main
        paths:
            - "tenant-service/**"

jobs:
    Checkout-and-login:
        runs-on: ubuntu-latest

        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_HUB_USERNAME}}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and Push the Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./tenant-service/Dockerfile
                  push: true
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tenant-service:dev
